spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url:
    username: sa
    password:
    driver-class-name:
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      password: 1


jwt:
  token:
    access-token-secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
    access-token-expire-length: 300000
    issuer: jihongha
